create table "public"."Holiday" (
    "id" bigint generated by default as identity not null,
    "status" text,
    "authoriser" bigint,
    "authorisingProjectCode" text
);


alter table "public"."Holiday" enable row level security;

create table "public"."HolidayTimeEntry" (
    "holidayId" bigint not null,
    "timeEntryId" bigint not null
);


alter table "public"."HolidayTimeEntry" enable row level security;

create table "public"."ResourceManager" (
    "id" bigint generated by default as identity not null,
    "userId" uuid,
    "projectCode" text
);


alter table "public"."ResourceManager" enable row level security;

alter table "public"."Project" drop column "requiresTask";

alter table "public"."TimeEntryType" drop column "requiresApproval";

alter table "public"."TimeEntryType" add column "isOvertime" boolean default false;

CREATE UNIQUE INDEX "HolidayTimeEntry_pkey" ON public."HolidayTimeEntry" USING btree ("holidayId", "timeEntryId");

CREATE UNIQUE INDEX "Holiday_pkey" ON public."Holiday" USING btree (id);

CREATE UNIQUE INDEX "ResourceManager_pkey" ON public."ResourceManager" USING btree (id);

alter table "public"."Holiday" add constraint "Holiday_pkey" PRIMARY KEY using index "Holiday_pkey";

alter table "public"."HolidayTimeEntry" add constraint "HolidayTimeEntry_pkey" PRIMARY KEY using index "HolidayTimeEntry_pkey";

alter table "public"."ResourceManager" add constraint "ResourceManager_pkey" PRIMARY KEY using index "ResourceManager_pkey";

alter table "public"."Holiday" add constraint "Holiday_authoriser_fkey" FOREIGN KEY (authoriser) REFERENCES "ResourceManager"(id) not valid;

alter table "public"."Holiday" validate constraint "Holiday_authoriser_fkey";

alter table "public"."Holiday" add constraint "Holiday_authorisingProjectCode_fkey" FOREIGN KEY ("authorisingProjectCode") REFERENCES "Project"("projectCode") not valid;

alter table "public"."Holiday" validate constraint "Holiday_authorisingProjectCode_fkey";

alter table "public"."HolidayTimeEntry" add constraint "HolidayTimeEntry_holidayId_fkey" FOREIGN KEY ("holidayId") REFERENCES "Holiday"(id) not valid;

alter table "public"."HolidayTimeEntry" validate constraint "HolidayTimeEntry_holidayId_fkey";

alter table "public"."HolidayTimeEntry" add constraint "HolidayTimeEntry_timeEntryId_fkey" FOREIGN KEY ("timeEntryId") REFERENCES "TimeEntry"(id) not valid;

alter table "public"."HolidayTimeEntry" validate constraint "HolidayTimeEntry_timeEntryId_fkey";

alter table "public"."ResourceManager" add constraint "ResourceManager_projectCode_fkey" FOREIGN KEY ("projectCode") REFERENCES "Project"("projectCode") not valid;

alter table "public"."ResourceManager" validate constraint "ResourceManager_projectCode_fkey";

alter table "public"."ResourceManager" add constraint "ResourceManager_userId_fkey" FOREIGN KEY ("userId") REFERENCES auth.users(id) not valid;

alter table "public"."ResourceManager" validate constraint "ResourceManager_userId_fkey";



